### ISSUE TITLE
Integration with AWS IoT: Store CA's on Gateway so it could connect directly to AWS IoT Core

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#528] opened 2022-05-18 14:52 UTC
X.509 client certificate + CA support would be best option

**Comment by ojousima** [comment] 2022-07-30 09:47
Is this a duplicate of #476

**Comment by laurijamsa** [comment] 2022-11-09 07:48
> Is this a duplicate of #476?

@TheSomeMan can we close this?

**Comment by laurijamsa** [comment] 2023-05-11 06:58
This is a duplicate of #476, closing.

**Closed by laurijamsa** 2023-05-11 06:58 UTC
Labels: enhancement
