### ISSUE TITLE
Gateway CSS doesn't always load

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#289] opened 2021-08-02 09:45 UTC
This is possibly related to #253, image below. This was the view when browsing to 10.10.0.1, fixed in refresh
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/2360368/127841168-70b9681c-c0ac-47f4-a48c-3dbbed376468.png">

**Comment by laurijamsa** [comment] 2021-08-24 03:59
Haven't seen this in some time with the latest builds. Closing, but feel free to reopen if needed.

**Comment by markoaamunkajo** [comment] 2022-08-31 03:31
QA passed, not spotted anymore

**Comment by laurijamsa** [comment] 2022-08-31 08:45
Tried to configure build 708 using iPhone SE:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1311912/187637169-c345e125-ee9b-42a7-aa23-4f42c8bc0249.png">

Full log:


[708-erase-flash-configure-using-iphone-se.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9460043/708-erase-flash-configure-using-iphone-se.log)

**Comment by TheSomeMan** [comment] 2022-09-03 14:24
This problem is caused by two reasons:
1. We are currently sending HTTP/1.1 responses, and sometimes the browser may try to reuse a previously opened connection, but we don't support it. This fix is trivial, just need to change the HTTP header.
2. The accepted connection is closed in LWIP immediately after establishment due to an overflow of the "acceptmbox" queue in the the "accept_function" function. Increasing of the value of macro DEFAULT_ACCEPTMBOX_SIZE from the default value 6 to 32 effectively eliminates the problem.

Although increasing of DEFAULT_ACCEPTMBOX_SIZE reduces probability of the problem significantly, it still can manifest itself if there are other applications on the PC, except the browser, which make a lot of requests to HTTP-servers.
Another way to reduce the probability of the problem is to join html/css/js (if possible, into one file).

**Closed** 2022-09-04 14:44 UTC

**Comment by ojousima** [comment] 2022-09-07 15:56
This does not pop up to me after https://github.com/ruuvi/esp32-wifi-manager/issues/209

**Comment by laurijamsa** [comment] 2022-09-12 08:22
I haven't tested really extensively but so far I haven't seen broken the css issue on the build 719.
