### ISSUE TITLE
When reconfiguring gateway, gateway crashes after the "DHCP page".

### ISSUE THREAD

**Issue by sj3fk3** [ruuvi/ruuvi.gateway_esp.c#347] opened 2021-09-03 19:11 UTC
The GW is setup to use DHCP and is connected via ethernet. When I do a re-configure the GW crashes after the network-tab. It doesn't matter if I select DHCP or manual set IP, the gateway will crash. If I power cycle the GW fast enough it will continue to the next page and I can finish the re-configure.

**Comment by laurijamsa** [comment] 2021-09-03 19:21
Could you share serial port logs? That would help us to find the cause. Connect the Gayeway using usb to your computer and open a serial port terminal app such as Putty or Minicom.

**Comment by markoaamunkajo** [comment] 2021-12-08 13:45
Cannot reproduce anymore, moving this to done

**Closed by markoaamunkajo** 2021-12-08 13:45 UTC
