### ISSUE TITLE
1.9.0 Wifi disconnection during config

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#423] opened 2021-11-03 15:53 UTC
Description:

Got a surprise disconnection and WiFi hotspot activated:
I (62904) http_server: [http_server] Respond: 200 OK
I (63914) ruuvi_gateway: [main] MAIN_TASK_SIG_DEACTIVATE_WIFI_AP
I (63914) wifi_manager: [main] wifi_manager_stop_ap
I (63916) wifi_manager: [wifi_manager] MESSAGE: ORDER_STOP_AP
I (63922) wifi_manager: [wifi_manager] Configure WiFi mode: Station
I (63930) wifi:mode : sta (94:b9:7e:4e:b2:68)
I (63933) wifi_manager: [sys_evt] WIFI_EVENT_AP_STOP
I (63940) wifi_manager: [wifi_manager] MESSAGE: ORDER_CONNECT_STA
I (63945) wifi_manager: [wifi_manager] MESSAGE: ORDER_DISCONNECT_STA
I (63953) wifi:state: run -> init (0)
I (63956) wifi:pm stop, total sleep time: 0 us / 60179523 us

I (63962) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (63968) wifi_manager: [sys_evt] WIFI_EVENT_STA_DISCONNECTED
I (63976) ruuvi_gateway: [wifi_manager] callback: on_disconnect_sta_cmd
E (63978) TRANS_SSL: ssl_poll_read select error 113, errno = Software caused connection abort, fd = 54
I (63982) wifi_manager: [wifi_manager] MESSAGE: EVENT_STA_DISCONNECTED with Reason code: 8
E (63992) MQTT_CLIENT: Poll read error: 0, aborting connection
I (64001) wifi_manager: [wifi_manager] event_bits & WIFI_MANAGER_REQUEST_STA_CONNECT_BIT
I (64009) MQTT: [mqtt_task] MQTT_EVENT_DISCONNECTED
I (64016) wifi_manager: [wifi_manager] Set STA IP String to: 0.0.0.0
I (64022) LEDS: [mqtt_task] leds_indication_network_no_connection
W (64029) ruuvi_gateway: [wifi_manager] Wifi disconnected
I (64036) LEDS: [mqtt_task] LED: Start blinking, interval: 200 ms, duty cycle: 50%
I (64042) LEDS: [wifi_manager] leds_indication_network_no_connection
I (64056) LEDS: [wifi_manager] LED: Start blinking, interval: 200 ms, duty cycle: 50%
I (64065) ADV_POST_TASK: [adv_post_task] Handle event: NETWORK_DISCONNECTED
I (64066) TIME: [time_task] Deactivate SNTP time synchronization
I (64066) LEDS: [main] leds_indication_network_no_connection
I (64085) LEDS: [main] LED: Start blinking, interval: 200 ms, duty cycle: 50%
I (64093) ruuvi_gateway: [main] free heap: 115276
W (64171) ADV_POST_TASK: [rx_parse_task] Can't send, MQTT is not connected yet

Steps to replicate:
1) Gateway running v1.8.3, connected to MQTT broker, WiFi connection
2) Connect to Gateway over LAN, run manual update to v1.9.0
3) Connect to Gateway configuration over LAN after update
4) ??? Wait for 60 seconds for WiFi hotspot signal? 
5) Disconnection, WiFi hotspot comes active

**Comment by markoaamunkajo** [comment] 2021-11-03 15:55
[log_excerpt.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7468898/log_excerpt.txt)

Watchdog reboots the GW in 1 hour and it connects to WiFi

In short, the update was successful and GW connected via MQTT, marking new partition as valid. Timer I (3910) ruuvi_gateway: [main] Start AP timer for 60 seconds is started but never stopped, and in 60 seconds the WiFi connection drops. After 3600 seconds watchdog reboots the gateway, GW connects to WiFi and starts working normally

I'll retry v1.9.0->v1.8.2->v1.9.0, this time without connecting to configuration hotspot to better simulate automated update

**Comment by ojousima** [comment] 2021-11-03 15:57
Edited title, this is observed on 1.9.0 after update from 1.8.3

**Comment by TheSomeMan** [comment] 2021-11-08 05:42
This problem was caused by #426 and #428, it was fixed in v1.9.1

**Closed by TheSomeMan** 2021-11-08 05:42 UTC
Labels: bug

**Comment by markoaamunkajo** [comment] 2021-11-23 15:02
QA passed
