### ISSUE TITLE
Test: rebooting with long press activates gateway

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#705] opened 2023-03-03 01:48 UTC
Description:

Configured and using ethernet cable connected
Custom http target configured
Pressed 10 seconds hardware button
Red indicator blinked
Then wifi hotspot got activated
After about 1 min started using ethernet and auto configured

Expected:
Works directly with ethernet and auto configures

**Comment by TheSomeMan** [comment] 2023-03-03 05:32
> Expected:
> Works directly with ethernet and auto configures

No, that's not expected. This is done on purpose because if you have an Ethernet cable connected and want to reconfigure the Gateway, you can erase the configuration and connect to WiFi access point immediately, and you do not need to disconnect the Ethernet cable to prevent auto-configuration.
If you do not want to wait one minute before autoconfiguration is performed, you can simply reboot the gateway after erasing the configuration. On the second boot the autoconfiguration will be carried out immediately after the reboot.

**Comment by markoaamunkajo** [comment] 2023-03-08 09:28
@TheSomeMan I did same steps as Lauri and hotspot was activated after long press when ethernet was connected.
But in the comment above you say that it's done on purpose.
Is this expected then?

**Comment by TheSomeMan** [comment] 2023-03-08 09:39
> @TheSomeMan I did same steps as Lauri and hotspot was activated after long press when ethernet was connected. But in the comment above you say that it's done on purpose. Is this expected then?

Yes, it's expected. Otherwise, you always need to disconnect the Ethernet cable before erasing the configuration and if it is not disconnected the default configuration will be applied immediately, which is not always the expected behavior.

**Comment by ojousima** [comment] 2023-03-11 12:24
Marking as done

**Closed by ojousima** 2023-03-11 12:24 UTC
